credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "docker"
          id: "docker"
          password: "{AQAAABAAAAAQSS7knWJDBifFAKDPYFbgmnt+jz6dNDkzLUTmXDvhNk0=}"
          scope: GLOBAL
          username: "balamood"
      - basicSSHUserPrivateKey:
          description: "ssh key"
          id: "ec2-user"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAAaQGxZRr635Hu+MJmphUbAXWmA9R4S5ArlXu/AHPSSjAapgHSvIrs4+OVgcGFPg56/gviwouDaFowYH2Jgq0B+T9EKMWmoe9qnHPfSpPP1/sTdD2n+Kwm+EyBPna+P4stgnsGnODAW2sng5bcdHNwx7UU0O8+QiJcSEEel4qnvyKKqVFfcm62e5yn/WIEZWYcbimgTyU/1viblnOEIXZr4q9bBnyJpWapOOATMXUmTvp+YqlwrcI30f4KncI3celjvIenEDGSCwgZZ4S1wSidx0dXLJrg74RjYQW3DnoLSW+R32aCWReQ/4DBZGnN7FTb+go7lJuS5ZwHd1ecgPEffFmgAmiGbE+gxoy1GQTOQfJoeyPtC7KOyPUIDxhILpsg3e+7E/JaNgnDqlpF1tpFEseRgCEgh+0dmQaF3oR3rpmuXZLNnfNEOE0qgNaGIGlOMu+RenNN5ICBitVmnwypcuhcltePuAbGPgK5qC5sueXqlfSc9H/mdnGexA1aLe2A/4ia1ZVUZrZ/uXEmp/hIZjN/U0wAKsSGIZzUz9aDuPs4vfNT73PKlouoHRRxs7Cazz82YH4wPE0nXhKcnFHoDS0sjL9deEu041YxluocKmg0i+MbFYZIv0bL64A+hvq3fhJWR08OB5cRJywjVwyPLK5ebqVy8kOIcI04kqgWWdKocynP+ENQ3hceCmNF/emRSX5YPlR6xr8d/6Li/iUV9IVsf6W2ZxY56fQBOoA1aFtLHIMWdC+2nj3uZvouZjcmwShTQa6Lh5h88raJhrDWtlkpkiFS7QGSFcJNA6D4cCwTSAw6FNCA0eAswXb/q3iH8Qc9gq+IXAVkO4QJ6Ix1nKbILesqUIUHCgoFE0fU01gy+u7dG8s0GSOGb1FeTh3ChJvNMW+bOr1z0k5qtuebQsKi4T6otleYvtChS09g7bgi84tDaOhtDvyV2bL2Rdfp0QSE6HfyfmW+CaJ2tr51NVzk2iPmkxneWyIJGM1m3w854IkTWz2i0pRj+cS3PEaJGTpYcwmdzZGT6inwY/VZH/M1PFVJLICI4YoBz1WKd686yV20xWjqMvoBpmimE3Om7Ys0bl7H1PEzwSQqkQ2Rf8cO9pLGiCxDqLqU2wKltJs0Z99fNYJT0zHLxCiGKGSgB/yHr03tldpf4LROoDrUsBWyfoHyklAh29ThqPt/Mzf9A7lOYvJarTS3riugdjsCFHGlSYMHnKyA9XoP2uJNlbWae5bx0R/XiMN3POIKoQ0eg631ZO2NfF1H//PHXwU/M2jpNecJ966hk+bZTOL1/NqjSo/krhhJP7PJ1X6fd4g8FfqhcIVeQo6pnom1z3NEhfyorh6wn/jxdyMtxsVacoTwadWmtwnMnR7kK2hryTxukXlWavh5Z/DU26Wdr0kZ43303Pw8cG1ilJhggfZ/gFcBBNZwj04IUQ/Dyd94vZutNJjVwqy4ZXUcO7p2+pscwnFQ83jGc2n/+WWzIASMe5VKDzt3IrapSeS0+wkzCYp6v2kabefcBqHi903d4/fKBeXg8JOXKBDRkkLtMAExNZz+CFw30IHAJrmZlK9mKreaf78msK55gjTTiapolVcOXOWZP4I5MJJ6Cg6j2x4TKaAWgB5/DPZGxKzU/STct1dLUdRzIt3FmZ0fySaGdxhpr9SJiPHdnqRpS23ZMjsAELBGRktjSpMx5ZWct+8FyEyFzomYX1lpFK0OcGzJ2PkhFOQ7YCgyD4UzmBwqohhG0Cdh/1p8SxT+Lifv3Sm+zxBnkAR68Pl7tcybevAdKSHNbgFbO6esQxCF/3lUY8qWiD2KGCojUj6SkzuP7/h7AEALZ6Aq07Gy+AJfHO+ghbMmj7OCWRBnkuAX3hcLsLcUC3BnFVG7VGkvIxaojx95TbzDyQXhApGY/ctERKR8xtAOVNP+jbwXLl8PKwJ1hwYDXoIz8PGCeVdHPFx6CpHjw2lYaMuNGdzwZhPc4khLQ9Gmegwz6sYr1CDlAR4p33/eFjuV5Ikz1AASnStTvYptSnbOY82KPb0VGU9MfYvB//5yu3/WElt0fCVoYbo2XjVp+F7+ue6meTPihJZchlg+1fuRJswzgQWJjed2nN7LLbXmbiJBKGudgU+d0rx/cAfPfpUt9KU3Fsz8pwSlvb9aHfrgWrhYbpu6f/SAUW6DDY5DYdLi8YRWEaRTyzLi6duFY8Byodh86U7PzGXj0xxLdup46yYqqdnIMXy6NNViHpbBHEDMVSi0BJVb1XnPrM2a/nbw==}"
          scope: GLOBAL
          username: "ec2-user"
      - file:
          description: "Kube config"
          fileName: "kubeconfig_assesment1"
          id: "kube_config"
          scope: GLOBAL
          secretBytes: "{PMk19+SbBdMHQhDHmPz55olNb5bJ/UaEFiQdcZNEYpOZG0MdfXE/9V1+pYqjPkCpdGpYY6WUg19GBwm32pV9zfHWjNMsnQU/ilkuiTlAbcuWvPRqXDgOTwmv4K/qMhYghoJi4nSZG+m3j2nojZZem+kcW3p9TcNZi1LxYBwZPiBqy9pOejJHpI8jCgGHwIul5y2MCpQ3awPNU8GuXIWGKJNVBLqYG7t4W7p6LV89gfcWM2LROSzNIHEKNq/baW+d2rRuBB/c4alGKguEiN/ivnk/ACBVSDXeGzU5XQ7JfNAUHmURZEDWo+zgHuYwQeWh6IyvZ7M6I3IhaTHhGR0nssLHQK1urIvPidTRXYS2urmypL8DTcjb0gkUWzOd5zkSW+sBXLDs8TRyV1jZwR3GGCMk4EUiW1dgBpgdJLxB+vw8SkKTBPM54VfYla7J7zKlIF/ORxLokkfHqxhTavDzxG1xi1tNgdAn1moBXqgN4tEofPMiVzSU7EJSNVbWz34pebIfiAnU8fOQuWqQ67ccrP0JzY+kkEtcCRZ17E0bUuiegO2wiW1oyCKX9dGg7MpzG+ZYkmqO3M9feKXeAOhfaepwIi2DWaj/a/X/td3DFdJ8KNd3DCfa8KcisndolgJfVFowfYMDkQ74QH7u6p54d6bljSVxBp+Lg8tUj2mOfIZ7dXH5WNaSXLf3aHd+w378J129bCyq0tPKXjAZRR05AfQpbSO7BBr6+S7Qb08w6pCXrLc84oGnvnjuy8LSSbGGA+Gs7OE5xeIEiXZsLZ00yr6L+pl3xKDU3WrvPt0e/1l5x1K2V1BXuNArxHxBViVUEF2MpQ2Xk0qo7qgYVjnkde0YAadg2stJpnWQWZt/WAUPU5Qys6HOByZ7I8DrLHdfsY/AlumtuWjo8JdvPem4dtMWBVRo4lKOpHqQNYk+0vT69sX7x9jfzDYQGaRxebsjQDgWgTFp77pVClmm+Ix4y21dHExzbEw1yO77gpEMJk7HDoZ+W+uKq9jip4WQkj+2gauLExqHNThEv+6rEOyXWrU4NwwglsT6AyQ90lZ7SIu1KyqvBTlvswn/JOGRzX3qXddffP1RDQhtxtQ0lYVeNJDnn84G9cqAtKO1uNrtEPz3aRNFgUG9FriovfmU7MdgN0R0diOZOp4wMmB4iWySO4N0efs/XEr7OLkHm+6Haj9NP1CAzX9BhmUnLIk5sy+Sv8AWjPJTqhZxCWRuQ5WIkq9J6jrBsAdR94MrmXccwYSpUGbzMU319JeV4jM8PFzGouQsXV1fFj6TyLwuGQKEIbUlCPaM3YpWfjY7xGwbKOUmkGPCdJjAHxSGymmJ61NU5HMcsgVWvJIBi9NwfkYtUaOwKm4620b6CfVQvLUrhF/EEbX3b1oApcORZ1UBWgyLCxa3MMMT0KAwccDNnB7ir0YnZpVyPZGFOBWBCYIPp9Mvg7EU7uGeuED0kPicdimHdf1svZWD65iR5tkF73n6RUQBVXb465OhTn2vqmsK/TgD9c0yH9KgX2qvc/QgNEmePWJq/ZCzg+fDuKqvX0DeC8DEgtdOUq/BTnpoqJiykH2P26os57Juket8/41Map8J8ALTzviPnozlQU4OGH/r9rOKicoFsAhzMlxotLgnauoQpO2XRjMNZyRgncRfoxrRwqvmnucmzuTCOF/Sy0eSfrgdjaj7W2bt9h7Jx5nOaixdTfpR3CKl8HGdDG6Y6qc2SDhrIsNjUhSr1VkeCcim5xPTnlNUUhSHyU5Zh5x8qUBWitcvjS7Vp+IQZQFruysLewRl2xCzVBZ1ZjiQB9/fIcw2MrpWOPyXaUpzVys3e6u8FDb1jUOOZs7C6TLBEHrmYKXlEgVV2UW0mS7GyoiTFvZEGN1XUgjsWle2WkrwuouennjDS78ZxhNaT5wjIpa7igwjlEoYBfnM5Mo6ChKBttmlNJN7m4ZvonCfFX0D599RN0XwTQ2gDVBT3gmxTKfHGCIG9ynG8eT1Ky8/vQQv6Bc7ydepqtjEJ0wtUP35sKsXF/IHVw/eKMOv3/LoMa+SX9jLGSn6+rUk/eoLR7ob3n3u5qrYIg+tZXIuMPXBqpzWBRAiaznR5Tr8oRD8vxjXNa1G56JiPj3gFvaJsjxnG7M7y7UoZEyBAJZxB0SWOhgsp60k1UD1Umqu7ai0lvIPGWOFgdzaN5TiVjVxaBss+GBIVX8TuaG0t4OmYpMnbelvadSsEtLWNltjTj5TwgTvaZAZRUb+VXyU6JHFaldQXNwFZkNT1GWjN2nKocB2dof5mJNNZF4d5/u38qsKlCJCdfDadNPEr2X9x2GrJmqpUzA67+7ZZ+B513Pi1yDJfd4ujKi7q2fKgt35MSuBPLnk0fVe6IaNxkChPZgfJ5zBxZ9+HKq4NQa6pWqehFTKHITEi+pnpUfqZUOvLZEfBtGSLnebftLEeQWITsIWd8i3YB9JIZECqGW6FS3NOhrfWr2WCgGi14NjPUXDG8baEfUWROZVWa5w6js8jvVHfm305FdzcBHB3pbFEVM5fd4etSYQd76P+tSY1kVawovjA3PLyO4XG+uHkrfrKAOLf/uDF9BbuDD9D1hon6uLjAvRba4OINmEXy+MTiE3E99N8TlWBgAgjZzHD/Hgd/37ryqCocxWieLrJWOUc59Hul1fk5rkyb0wKk29TCt1PSGQNFYpk++H3gj1UIPuZOaR5/XO8NNrZWP1wPjQHs+mMt9xDZ89vImB5M8G7+iPRJreQUrM12Xm0rTiXS3XC/9oghzae8NpVs5DjuuLaIIAyKAze1+8AyRA9So/Z0mDWPnsmoBNWCOeOWRZI9GcZ9mM6nx3ZaoE43C4PT3uTbTH/1iqAdU0lJPYdQTWN1MNN/RRO38ouLNMYJ/sHdQzXE/3tfZwUzXARoz250tAkKGsJGnjmLWkdspDmdZHzMHdjk2xsMbGPeezlLfN/adhLkYENCb53L992p5RQmVQo/7rCg+E+XdHjvCcSBS70yulOVkvzrFql+ritxNXuOus9sJuuhc9qBfCAjYcT1Oj1LXvJPApL+aewoY8y1J/dtjMa7F3LD+SOdzNCobK/lEh8EI8ux8dzsC6bBBeXyNMayVojEhFeGJHgrQuwhPPRNmtzm2mXdnMLCs8gQAYkO7tGkfSpVQNkQ==}"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "GROUP:Overall/Read:authenticated"
      - "USER:Overall/Administer:admin"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: "triggeringUsersAuthorizationStrategy"
  sSHD:
    port: -1
  scriptApproval:
    approvedScriptHashes:
    - "SHA512:3f205299bef2fe3329258a42f2c60d332cc35ccb41a3ca0512d7869c6aff4561ff708c48123b4f7c3dec33ccca30d54fb8b9b51b5bc7070f96236d11a3f0bdcb"
    approvedSignatures:
    - "method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object"
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            daysToKeepStr: "1"
            numToKeepStr: "1"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  injectionConfig:
    allowUntrusted: false
    enabled: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pipeline-model-docker:
    dockerLabel: "docker"
    registry:
      credentialsId: "docker"
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
